/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pr15ciutatsedgar;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author edgarmunoz
 */
public class Monumentos extends javax.swing.JFrame {

    /**
     * Creates new form Monumentos
     */
     private int selectedCombo = 0;     
     private int selectedPais = 0;
     private String selectedText = "";
     
     private File fileContent = new File("");                            
     private String programRoot = fileContent.getCanonicalPath();  
     private ArrayList<Pais> PaisData = new ArrayList<Pais>(); 
     
      private String[] marseille = {
            programRoot + "/resources/marseille_monumento0.jpg",
            programRoot + "/resources/marseille_monumento1.jpg",
            programRoot + "/resources/marseille_monumento2.jpg"
        };
         
        private String[] roma = {
            programRoot + "/resources/roma_monumento0.jpg",
            programRoot + "/resources/roma_monumento1.jpg",
            programRoot + "/resources/roma_monumento2.jpg"
        };
         
        private String[] reikiavik = {
            programRoot + "/resources/reikiavik_monumento0.jpg",
            programRoot + "/resources/reikiavik_monumento1.jpg",
            programRoot + "/resources/reikiavik_monumento2.jpg"
        };
               
    public Monumentos() throws IOException {
        initComponents();                       
    }
     private ArrayList<Pais> getPictures(String[] archivosImagen) throws IOException{                                
         ArrayList<Icon> imagenes = new ArrayList<Icon>();           
         ArrayList<Pais> PaisData = new ArrayList<Pais>();        
         
         for (String archivo : archivosImagen){            
            File file = new File(archivo); 
            BufferedImage newImage = ImageIO.read(file);              
            Image currentPicture = newImage.getScaledInstance(480, 256, Image.SCALE_SMOOTH);
             
            imagenes.add(new ImageIcon(currentPicture));                   
         }
         
         Pais pais = new Pais(imagenes);             
         pais.setText(selectedText);
         
         PaisData.add(pais); 
         return PaisData;
    }
     
    public void setPaisId(int selectedPais) throws IOException{
        this.selectedPais = selectedPais;
        
        if(selectedPais == 0) {  
            ArrayList<Pais> marseillePais = getPictures(marseille);
            selectedText = "Esto es la marseille";
            PaisData = marseillePais;            
        } else if (selectedPais == 1){             
            ArrayList<Pais> romaPais = getPictures(roma);                             
            selectedText = "Esto es la roma";
            PaisData = romaPais;
        } else if (selectedPais == 2){             
            ArrayList<Pais> reikiavikPais = getPictures(reikiavik);                                                         
            selectedText = "Esto es reikiavik";            
            PaisData = reikiavikPais;
        }
        
        
    }
    
    
    private void setjLabelPictureImage(ArrayList<Pais> pais, int ID){        
        for (Pais paisInfo : pais){ 
            for (Icon element : paisInfo.getPictures()) {           
                if(paisInfo.getPictures().indexOf(element) == ID) {                                                 
                    jLabel1.setIcon(element);           
                }                    
            }      
        }         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jToggleButton1)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        selectedCombo = jComboBox1.getSelectedIndex();  
        setjLabelPictureImage(PaisData, selectedCombo);
        jLabel1.setText(selectedText);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        jLabel1.setVisible(jToggleButton1.isSelected());
        jComboBox1.setVisible(jToggleButton1.isSelected());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Monumentos().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Monumentos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
